name: DuelPlugin
version: 1.0
main: avx.duel.DuelPlugin
api-version: 1.20
commands:
  duel:
    description: Duel command system.
    usage: /duel <player> | accept | deny | forfeit | leaderboard | setarena
